# Generated by Django 3.0.4 on 2020-03-17 21:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('language', models.CharField(max_length=10)),
                ('date', models.CharField(max_length=15)),
                ('movie_id', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'db_table': 'movies',
            },
        ),
        migrations.CreateModel(
            name='Movie_Info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_info', models.TextField()),
                ('image_name', models.CharField(max_length=50)),
                ('movie', models.OneToOneField(db_column='movie_id', on_delete=django.db.models.deletion.CASCADE, related_name='movie', to='onemovie.Movies', to_field='movie_id')),
            ],
            options={
                'db_table': 'movie_info',
            },
        ),
    ]
